### PR TITLE
add support to manually restart by typing "rs"

### PR DESCRIPTION
**Pull request by win-t**
inspired by [nodemon](https://www.npmjs.com/package/nodemon).
sometime you need to restart the app, but don't want to restart CompileDaemon directly

### CODE REVIEW

**Comment by githubnemo** [comment]
Thanks for the contribution. Is this really easier than saving a code file and thus reinvoking the job queue?

**Comment by win-t** [comment]
sometime you need to invalidate in-ram memory cache

**Comment by win-t** [comment]
and also, I need to force-kill (by send signal without register hanlder for it) the app to see how the app handle corrupt data when startup again,
And yes, writing automation test is the right answer here, but this gives quick dirty solution for that purpose

**Comment by win-t** [comment]
but I think this is wrong approach, what if the program itself using stdin

**Pull request closed without merging**
